build: false

environment:
  matrix:
    
  - PYTHON: "C:\\Python34"
    PYTHON_VERSION: "3.4.0"
    PYTHON_ARCH: "64"
    
  - PYTHON: "C:\\Python34"
    PYTHON_VERSION: "3.4.0"
    PYTHON_ARCH: "32"
    
  - PYTHON: "C:\\Python35"
    PYTHON_VERSION: "3.5.2"
    PYTHON_ARCH: "32"
    
  - PYTHON: "C:\\Python35"
    PYTHON_VERSION: "3.5.2"
    PYTHON_ARCH: "64"	
    
  - PYTHON: "C:\\Python36"
    PYTHON_VERSION: "3.6.0"
    PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%PYTHON%/python.exe setup.py install"

test_script:
  - "%PYTHON%/python.exe -m opem test"