{% set name = "opem" %}
{% set version = "1.4" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/ECSIM/opem
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.6
    run:
        - art >0.7
        - requests >=2.20.0
        - python >=3.6
about:
    home: https://github.com/ECSIM/opem
    license: MIT
    license_family: MIT
    summary: OPEM (Open Source PEM Fuel Cell Simulation Tool)
    description: |
        Modeling and simulation of proton-exchange membrane fuel cells (PEMFC) may work as a powerful tool in the research & development of renewable energy sources. The Open-Source PEMFC Simulation Tool (OPEM) is a modeling tool for evaluating the performance of proton exchange membrane fuel cells. This package is a combination of models (static/dynamic) that predict the optimum operating parameters of PEMFC. OPEM contained generic models that will accept as input, not only values of the operating variables such as anode and cathode feed gas, pressure and compositions, cell temperature and current density, but also cell parameters including the active area and membrane thickness. In addition, some of the different models of PEMFC that have been proposed in the OPEM, just focus on one particular FC stack, and some others take into account a part or all auxiliaries such as reformers. OPEM is a platform for collaborative development of PEMFC models.

        Website: http://opem.ecsim.site

        Repo: https://github.com/ECSIM/opem
extra:
    recipe-maintainers:
        - ecsim
